name: Greeter
description: Composite action to greet the world


inputs:
  name_to_greet:
    description: 'Name to greet'
    required: false
    default: 'World'

runs:
  using: "composite"
  steps:
    - name: Say Hello
      run: echo "Hello, ${{ inputs.name_to_greet }}!"
      shell: bash